export const menu = [
  {
    name: "Điều khiển Hệ thống",
    title: "Điều khiển Hệ thống",
    id: "DKHT",
    numberOfFiles: 6,
  },
  {
    name: "Màn hình điểm thi",
    title: "Màn hình điểm thi",
    id: "MHDT",
  },
  {
    name: "Khởi động",
    title: "Khởi động",
    id: "KD",
    round: [
      {
        numQuestion: 8,
      },
      {
        numQuestion: 12,
      },
      {
        numQuestion: 16,
      },
    ],
    waiting: 3,
    url: "video/Tiên phát chế nhân.mp4",
  },
  {
    name: "Vượt chướng ngại vật",
    title: "Vượt chướng ngại vật",
    id: "VCNV",
    time: 15,
    url: "video/Công thành chiến.mp4",
  },
  {
    name: "Tăng tốc",
    title: "Tăng tốc",
    id: "TT",
    time1: 10,
    time2: 20,
    time3: 30,
    time4: 40,
    score1st: 40,
    score2nd: 30,
    score3rd: 20,
    score4th: 10,
    url: "video/Tốc chiến tốc thắng.mp4",
  },
  {
    name: "Về đích",
    title: "Về đích",
    id: "VD",
    time10: 10,
    time20: 15,
    time30: 20,
    scoreMinus10: 5,
    scoreMinus20: 10,
    scoreMinus30: 15,
    scoreStar10: 20,
    scoreStar20: 40,
    scoreStar30: 60,
    url: "video/Mã đáo thành công.mp4",
  },
  // {
  //   name: "Câu hỏi sở trường",
  //   title: "Câu hỏi sở trường",
  //   id: "ST",
  //   time10: 10,
  //   time20: 15,
  //   time30: 20,
  //   scoreMinus10: 5,
  //   scoreMinus20: 10,
  //   scoreMinus30: 15,
  //   scoreStar10: 20,
  //   scoreStar20: 40,
  //   scoreStar30: 60,
  // },
  {
    name: "Câu hỏi phụ",
    title: "Câu hỏi phụ",
    id: "CHP",
    time: 15,
  },
];

export const VDConst = {
  name: "Về đích",
  title: "Về đích",
  id: "VD",
  time10: 10,
  time20: 15,
  time30: 20,
  lab10: 20,
  lab20: 30,
  lab30: 40,
  scoreMinus10: 5,
  scoreMinus20: 10,
  scoreMinus30: 15,
  scoreStar10: 20,
  scoreStar20: 40,
  scoreStar30: 60,
};
